### ISSUE TITLE
Add a mixin to convert query arguments into query params

### ISSUE THREAD

**Issue by yezyilomo** [yezyilomo/django-restql#163]
- This will allow the library to work with any filter backend and any pagination class without requiring integration. 
- With this `DEFAULT_BASE_FILTER_BACKEND` setting will not be needed anymore as all filter backends will be working out of the box.

Will be able to do 
- `GET /users/?query=(page: 2){id, name}`
- `GET /users/?query=(limit: 5, offset: 10){id, name}`
- `GET /users/?query=(id: 3, name: Bob){id, name}`

**Comment by TheUKDave** [comment]
Can you give details of user migration from previous versions? Having upgraded today, the setting is not just deprecated, but breaks entirely because of it.

I currently use `rest_framework.DjangoFilterBackend`, so do I remove both the RESTQL setting, and also `DEFAULT_FILTER_BACKENDS` pointing to `django_restql.filters.RESTQLFilterBackend` inside of my REST_FRAMEWORK settings?

**Comment by yezyilomo** [comment]
You just set
 ```py
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}
```
