### ISSUE TITLE
amazing project! what about supporting drf-dynamic-fields syntax too?

### ISSUE THREAD

**Issue by jsmedmar** [yezyilomo/django-restql#26]
Very nice work. In the readme says:

> My intention is to extend the capability of [drf-dynamic-fields ](https://github.com/dbrgn/drf-dynamic-fields)

What about supporting the regular django syntax too? Something like:

    fields=id,username,groups__id,groups__name

It seems we could write a pre-processing step to convert `fields` into `query`:

```python
from collections import defaultdict


def fields2query(fields_string):
    fields_list = [i for i in (fields_string or "").split(",") if i]

    def _f2q(fields_list):
        query, fields_dict = "", defaultdict(list)

        for i in sorted(set(fields_list)):
            split = i.split("__", 1)

            if len(split) == 2:
                fields_dict[split[0].strip()].append(split[1].strip())
            else:
                fields_dict[split[0].strip()] = []

        for field, nested in sorted(fields_dict.items()):
            new_query = (field + ' ' + _f2q(nested)) if nested else field
            query = ", ".join(i for i in [query, new_query] if i)

        return "{{{0}}}".format(query) if query else query

    return _f2q(fields_list)
```

I wrote tests also:

```python
def test_fields_to_query():
    # simple case with empty string
    assert fields2query("") == ""

    # weird commas
    assert fields2query(",,") == ""

    # one field only
    assert fields2query("username") == "{username}"

    # two fields
    assert fields2query("username,id") == "{id, username}"

    # funny commas
    assert fields2query("username,,id,,,") == "{id, username}"

    # one level nested
    assert (
        fields2query("username,id,location__country, location__region")
        == "{id, location {country, region}, username}"
    )

    # two level nested
    assert (
        fields2query(
            "username,id,location__country__capital, location__country__population,location__region"
        )
        == "{id, location {country {capital, population}, region}, username}"
    )

    # two, two level nested
    assert (
        fields2query(
            "username,id,location__country__capital, location__country__population,location__region, location__region__timezone"
        )
        == "{id, location {country {capital, population}, region {timezone}}, username}"
    )
```

## Implementation

We could by default support both syntax by checking if `__` is in `query` or if `query` does not start with `{`. Let me know if you would be interested in a PR.

I think this will be very attractive for [drf-dynamic-fields ](https://github.com/dbrgn/drf-dynamic-fields) users as we wouldn't need to refactor any of our code in order to benefit from this very nice package.

**Comment by yezyilomo** [comment]
Thanks for the feedback, I personally think GraphQL syntax is more cleaner than drf-dynamic-fields syntax, consider the following example, let's say user field is a nested field and we want to get id, name, email and age of a user, 
here is how we would do it with drf-dynamic-fields syntax 
`fields=user__id, user__name, user__email, user__age`

and here is how we would do the same thing with django-restql syntax

`query=user{id, name, email, age}`

Observations
- The former approach introduce redundancy(repeating user to every nested field, imagine fetching 10 nested field or more)
- The former approach tend to be long compared to django-restql approach
- The former approach doesn't tell much about the hierarchy of the fields. With django-restql approach it's clear that id, name, email and age fields are under user field and that's how it's going to be in a response.
- Also according to the zen of python "There should be one-- and preferably only one --obvious way to do it" I think supporting both syntax as you said is not a good idea, it can be confusing to library users.

Sure, implementing what you suggested could benefit those who transition from drf-dynamic-fields to django-restql but I don't think if it's worth implementing due to the reasons I mentioned above. Also django-restql use GraphQL like syntax is so it will be easier to those coming from GraphQL and those who want to shift from django-restql to GraphQL.

**Comment by jsmedmar** [comment]
👌🏼
