### ISSUE TITLE
Define query_parameter in settings file.

### ISSUE THREAD

**Issue by anudeepsamaiya** [yezyilomo/django-restql#84]
Currently to use a custom name for query parameter instead of default `query`, one has to modify fields every serializer that inherits from `DynamicFieldsMixin`.

Can this be define globally in settings file and `DynamicFieldsMixin` reads from it if available. Otherwise it uses default.

**Comment by yezyilomo** [comment]
Good idea but currently you don't have to modify `query_parameter_name` on every serializer which inherit `DynamicFieldsMixin` you can create your custom `DynamicFieldsMixin` which inherit `DynamicFieldsMixin`  and overrides `query_parameter_name` and then use it to all your serializers. I see your approach as a simple way to change a query parameter name that is instead of inheriting `DynamicFieldsMixin`  and overriding `query_parameter_name` you can just set `query_parameter_name` in settings file.

**Comment by yezyilomo** [comment]
@anudeepsamaiya I've realized that your idea could make `EagerLoadingMixin` independent of `DynamicFieldsMixin` which is great coz it's something we've been struggling to do.

**Comment by anudeepsamaiya** [comment]
@yezyilomo Thanks for such a wonderful library, but I think docs should explain both ways to declare a custom query name. 
For everywhere in my project I should be able to declare it in the settings file.
For specific case I should be able to inherit and modify in the child serializer.
