### ISSUE TITLE
Query Parameter should be allowed to declare in child classes and settings both.

### ISSUE THREAD

**Issue by anudeepsamaiya** [yezyilomo/django-restql#90]
@yezyilomo Thanks for such a wonderful library, but I think docs should explain both ways to declare a custom query name. 
For everywhere in my project I should be able to declare it in the settings file.
For specific case I should be able to inherit and modify in the child serializer.

_Originally posted by @anudeepsamaiya in https://github.com/yezyilomo/django-restql/issues/84#issuecomment-558571387_

Ref Merge Request #89

**Comment by yezyilomo** [comment]
@anudeepsamaiya The idea changing query name by overriding `DynamicFieldMixin` makes `EagerLoadingMixin` depend on `DynamicFieldsMixin` which makes it hard for `EagerLoadingMixin` to operate without `DynamicFieldsMixin`, we made `QUERY_PARAM_NAME` setting because we want to have a single reliable source of restql parameter name which can be used by both `DynamicFieldsMixin` and `EagerLoadingMixin` without depending on eachother.
